services:
  postgres-db:
    image: postgres:15-alpine
    container_name: enviro_postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5435:5432"
    volumes:
      - enviro_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: enviro_backend
    ports:
      - "8083:8080"
    environment:
      DB_HOST: postgres-db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      DB_DIALECT: postgres
    depends_on:
      - postgres-db

  frontend:
    build: ./frontend
    container_name: enviro_frontend
    ports:
      - "5176:80"
    depends_on:
      - backend

volumes:
  enviro_postgres_data: